import { Student } from "@/types";

// =========================================================================
// BASE DE DONNÉES OFFICIELLE DES ÉLÈVES — HÔTEL ÉCOLE AVENIDA LOMÉ
// Extraite des registres officiels (Relevés de notes & Fiches de présence)
// Classés rigoureusement par Année Académique & Filière
// =========================================================================

// Quartiers représentatifs de Lomé pour les adresses
const LOME_NEIGHBORHOODS = [
  "Dékon",
  "Tokoin Habitat",
  "Bè-Kpota",
  "Hedzranawoé",
  "Adidogomé",
  "Agoè-Assiyéyé",
  "Kodjoviakopé",
  "Nyékonakpoè",
  "Totsi",
  "Kégué",
  "Amoutivé",
  "Agbalépédogan",
];

// -------------------------------------------------------------------------
// 1. PROMOTION 2024 – 2025 : BTS / DUT 1ère Année (34 Étudiants)
// -------------------------------------------------------------------------
export const STUDENTS_2024_2025: Student[] = [
  {
    id: "std-801avn-24",
    registration_number: "801AVN-24",
    student_number: "ETU-2024-00801",
    last_name: "AFOLEHO",
    first_name: "Essi",
    gender: "F",
    birth_date: "2005-04-12",
    birth_place: "Lomé",
    nationality: "Togolaise",
    residence_neighborhood: "Dékon",
    phone: "+228 90 11 22 33",
    email: "e.afoleho@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "AFOLEHO Koffi",
    emergency_contact_phone: "+228 90 11 22 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 420000,
    remaining_fee: 0,
  },
  {
    id: "std-802avn-24",
    registration_number: "802AVN-24",
    student_number: "ETU-2024-00802",
    last_name: "AGBAHEY",
    first_name: "Toundé Jean Chrysotome",
    gender: "M",
    birth_date: "2004-11-20",
    birth_place: "Aného",
    nationality: "Togolaise",
    residence_neighborhood: "Tokoin Habitat",
    phone: "+228 91 22 33 44",
    email: "t.agbahey@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "AGBAHEY Michel",
    emergency_contact_phone: "+228 91 22 33 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 350000,
    remaining_fee: 70000,
  },
  {
    id: "std-803avn-24",
    registration_number: "803AVN-24",
    student_number: "ETU-2024-00803",
    last_name: "AGBE",
    first_name: "Solange",
    gender: "F",
    birth_date: "2005-08-15",
    birth_place: "Kpalimé",
    nationality: "Togolaise",
    residence_neighborhood: "Hedzranawoé",
    phone: "+228 92 33 44 55",
    email: "s.agbe@ecole-avenida.tg",
    boarder_status: "interne",
    emergency_contact_name: "AGBE Komla",
    emergency_contact_phone: "+228 92 33 44 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 420000,
    remaining_fee: 0,
  },
  {
    id: "std-804avn-24",
    registration_number: "804AVN-24",
    student_number: "ETU-2024-00804",
    last_name: "AGBODAN",
    first_name: "Afi Dona Victoire",
    gender: "F",
    birth_date: "2006-01-10",
    birth_place: "Lomé",
    nationality: "Togolaise",
    residence_neighborhood: "Bè-Kpota",
    phone: "+228 93 44 55 66",
    email: "v.agbodan@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "AGBODAN Paul",
    emergency_contact_phone: "+228 93 44 55 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 280000,
    remaining_fee: 140000,
  },
  {
    id: "std-805avn-24",
    registration_number: "805AVN-24",
    student_number: "ETU-2024-00805",
    last_name: "AKAKPO",
    first_name: "Yaovi Messanh François",
    gender: "M",
    birth_date: "2004-09-05",
    birth_place: "Tsévié",
    nationality: "Togolaise",
    residence_neighborhood: "Agoè-Assiyéyé",
    phone: "+228 90 55 66 77",
    email: "f.akakpo@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "AKAKPO Messanh",
    emergency_contact_phone: "+228 90 55 66 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 420000,
    remaining_fee: 0,
  },
  {
    id: "std-806avn-24",
    registration_number: "806AVN-24",
    student_number: "ETU-2024-00806",
    last_name: "AKPATCHA",
    first_name: "Abla Grace",
    gender: "F",
    birth_date: "2005-06-25",
    birth_place: "Atakpamé",
    nationality: "Togolaise",
    residence_neighborhood: "Kodjoviakopé",
    phone: "+228 91 66 77 88",
    email: "g.akpatcha@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "AKPATCHA Édouard",
    emergency_contact_phone: "+228 91 66 77 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 300000,
    remaining_fee: 120000,
  },
  {
    id: "std-807avn-24",
    registration_number: "807AVN-24",
    student_number: "ETU-2024-00807",
    last_name: "AMOUZOU",
    first_name: "Akossiwa Bienvenue",
    gender: "F",
    birth_date: "2005-12-14",
    birth_place: "Lomé",
    nationality: "Togolaise",
    residence_neighborhood: "Nyékonakpoè",
    phone: "+228 92 77 88 99",
    email: "b.amouzou@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "AMOUZOU Kodjo",
    emergency_contact_phone: "+228 92 77 88 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 420000,
    remaining_fee: 0,
  },
  {
    id: "std-808avn-24",
    registration_number: "808AVN-24",
    student_number: "ETU-2024-00808",
    last_name: "AMOUZOUHOIN",
    first_name: "Koffi Vivien",
    gender: "M",
    birth_date: "2004-03-30",
    birth_place: "Lomé",
    nationality: "Togolaise",
    residence_neighborhood: "Adidogomé",
    phone: "+228 93 88 99 00",
    email: "v.amouzouhoin@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "AMOUZOUHOIN Marc",
    emergency_contact_phone: "+228 93 88 99 11",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 250000,
    remaining_fee: 170000,
  },
  {
    id: "std-809avn-24",
    registration_number: "809AVN-24",
    student_number: "ETU-2024-00809",
    last_name: "ATAKPLA",
    first_name: "Ekoué Edem Alexis",
    gender: "M",
    birth_date: "2005-02-18",
    birth_place: "Aného",
    nationality: "Togolaise",
    residence_neighborhood: "Totsi",
    phone: "+228 90 99 00 11",
    email: "e.atakpla@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "ATAKPLA Alexis Senior",
    emergency_contact_phone: "+228 90 99 00 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 420000,
    remaining_fee: 0,
  },
  {
    id: "std-810avn-24",
    registration_number: "810AVN-24",
    student_number: "ETU-2024-00810",
    last_name: "AYA",
    first_name: "Kokou Winner",
    gender: "M",
    birth_date: "2004-07-22",
    birth_place: "Lomé",
    nationality: "Togolaise",
    residence_neighborhood: "Kégué",
    phone: "+228 91 00 11 22",
    email: "w.aya@ecole-avenida.tg",
    boarder_status: "interne",
    emergency_contact_name: "AYA Victor",
    emergency_contact_phone: "+228 91 00 11 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 380000,
    remaining_fee: 40000,
  },
  {
    id: "std-811avn-24",
    registration_number: "811AVN-24",
    student_number: "ETU-2024-00811",
    last_name: "BADAM",
    first_name: "Kokou Jean Pierre",
    gender: "M",
    birth_date: "2005-05-11",
    birth_place: "Sokodé",
    nationality: "Togolaise",
    residence_neighborhood: "Amoutivé",
    phone: "+228 92 11 22 33",
    email: "j.badam@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "BADAM Pierre",
    emergency_contact_phone: "+228 92 11 22 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 420000,
    remaining_fee: 0,
  },
  {
    id: "std-812avn-24",
    registration_number: "812AVN-24",
    student_number: "ETU-2024-00812",
    last_name: "BEREMWOUDOUGOU",
    first_name: "S. Yasmine",
    gender: "F",
    birth_date: "2006-03-19",
    birth_place: "Ouagadougou",
    nationality: "Burkinabé",
    residence_neighborhood: "Agbalépédogan",
    phone: "+228 93 22 33 44",
    email: "y.beremwoudougou@ecole-avenida.tg",
    boarder_status: "interne",
    emergency_contact_name: "BEREMWOUDOUGOU Ali",
    emergency_contact_phone: "+226 70 12 34 56",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 420000,
    remaining_fee: 0,
  },
  {
    id: "std-813avn-24",
    registration_number: "813AVN-24",
    student_number: "ETU-2024-00813",
    last_name: "BIDA",
    first_name: "Amiratou",
    gender: "F",
    birth_date: "2005-10-04",
    birth_place: "Kara",
    nationality: "Togolaise",
    residence_neighborhood: "Dékon",
    phone: "+228 90 33 44 55",
    email: "a.bida@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "BIDA Soulé",
    emergency_contact_phone: "+228 90 33 44 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1548142813-c348350df52b?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 320000,
    remaining_fee: 100000,
  },
  {
    id: "std-814avn-24",
    registration_number: "814AVN-24",
    student_number: "ETU-2024-00814",
    last_name: "COLLEY",
    first_name: "A. Edmond",
    gender: "M",
    birth_date: "2004-12-08",
    birth_place: "Lomé",
    nationality: "Togolaise",
    residence_neighborhood: "Tokoin Habitat",
    phone: "+228 91 44 55 66",
    email: "e.colley@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "COLLEY Georges",
    emergency_contact_phone: "+228 91 44 55 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 420000,
    remaining_fee: 0,
  },
  {
    id: "std-815avn-24",
    registration_number: "815AVN-24",
    student_number: "ETU-2024-00815",
    last_name: "d'ALMEIDA",
    first_name: "Ayi Larissio",
    gender: "M",
    birth_date: "2005-01-29",
    birth_place: "Aného",
    nationality: "Togolaise",
    residence_neighborhood: "Hedzranawoé",
    phone: "+228 92 55 66 77",
    email: "l.dalmeida@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "d'ALMEIDA Jean",
    emergency_contact_phone: "+228 92 55 66 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 390000,
    remaining_fee: 30000,
  },
  {
    id: "std-816avn-24",
    registration_number: "816AVN-24",
    student_number: "ETU-2024-00816",
    last_name: "DE SOUZA",
    first_name: "Afi Cylvia",
    gender: "F",
    birth_date: "2005-09-17",
    birth_place: "Lomé",
    nationality: "Togolaise",
    residence_neighborhood: "Bè-Kpota",
    phone: "+228 93 66 77 88",
    email: "c.desouza@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "DE SOUZA Francisco",
    emergency_contact_phone: "+228 93 66 77 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 420000,
    remaining_fee: 0,
  },
  {
    id: "std-817avn-24",
    registration_number: "817AVN-24",
    student_number: "ETU-2024-00817",
    last_name: "DICKEWU",
    first_name: "Afi Williana",
    gender: "F",
    birth_date: "2006-02-14",
    birth_place: "Lomé",
    nationality: "Togolaise",
    residence_neighborhood: "Kodjoviakopé",
    phone: "+228 90 77 88 11",
    email: "w.dickewu@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "DICKEWU William",
    emergency_contact_phone: "+228 90 77 88 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 350000,
    remaining_fee: 70000,
  },
  {
    id: "std-818avn-24",
    registration_number: "818AVN-24",
    student_number: "ETU-2024-00818",
    last_name: "DOMEGNI",
    first_name: "Léa Elie",
    gender: "F",
    birth_date: "2005-07-07",
    birth_place: "Kpalimé",
    nationality: "Togolaise",
    residence_neighborhood: "Nyékonakpoè",
    phone: "+228 91 88 99 22",
    email: "l.domegni@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "DOMEGNI Elie",
    emergency_contact_phone: "+228 91 88 99 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 420000,
    remaining_fee: 0,
  },
  {
    id: "std-819avn-24",
    registration_number: "819AVN-24",
    student_number: "ETU-2024-00819",
    last_name: "DOSSOU",
    first_name: "Abla Dona",
    gender: "F",
    birth_date: "2005-11-12",
    birth_place: "Lomé",
    nationality: "Togolaise",
    residence_neighborhood: "Agoè-Assiyéyé",
    phone: "+228 92 99 00 33",
    email: "d.dossou@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "DOSSOU Thomas",
    emergency_contact_phone: "+228 92 99 00 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 420000,
    remaining_fee: 0,
  },
  {
    id: "std-820avn-24",
    registration_number: "820AVN-24",
    student_number: "ETU-2024-00820",
    last_name: "DOSSOU",
    first_name: "Yayra Sandrine",
    gender: "F",
    birth_date: "2006-04-03",
    birth_place: "Lomé",
    nationality: "Togolaise",
    residence_neighborhood: "Adidogomé",
    phone: "+228 93 00 11 44",
    email: "s.dossou@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "DOSSOU Albert",
    emergency_contact_phone: "+228 93 00 11 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 310000,
    remaining_fee: 110000,
  },
  {
    id: "std-821avn-24",
    registration_number: "821AVN-24",
    student_number: "ETU-2024-00821",
    last_name: "EDOH",
    first_name: "Silvère",
    gender: "M",
    birth_date: "2004-08-27",
    birth_place: "Atakpamé",
    nationality: "Togolaise",
    residence_neighborhood: "Totsi",
    phone: "+228 90 11 33 55",
    email: "s.edoh@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "EDOH Paul",
    emergency_contact_phone: "+228 90 11 33 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 420000,
    remaining_fee: 0,
  },
  {
    id: "std-822avn-24",
    registration_number: "822AVN-24",
    student_number: "ETU-2024-00822",
    last_name: "EYOU",
    first_name: "Adjo Georgette",
    gender: "F",
    birth_date: "2005-10-18",
    birth_place: "Lomé",
    nationality: "Togolaise",
    residence_neighborhood: "Kégué",
    phone: "+228 91 22 44 66",
    email: "g.eyou@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "EYOU Georges",
    emergency_contact_phone: "+228 91 22 44 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 420000,
    remaining_fee: 0,
  },
  {
    id: "std-823avn-24",
    registration_number: "823AVN-24",
    student_number: "ETU-2024-00823",
    last_name: "HUNKPEVI",
    first_name: "Yaovi",
    gender: "M",
    birth_date: "2004-06-14",
    birth_place: "Vogan",
    nationality: "Togolaise",
    residence_neighborhood: "Amoutivé",
    phone: "+228 92 33 55 77",
    email: "y.hunkpevi@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "HUNKPEVI Yaovi Senior",
    emergency_contact_phone: "+228 92 33 55 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 370000,
    remaining_fee: 50000,
  },
  {
    id: "std-824avn-24",
    registration_number: "824AVN-24",
    student_number: "ETU-2024-00824",
    last_name: "KOTOKA",
    first_name: "Afi Honorine",
    gender: "F",
    birth_date: "2005-03-21",
    birth_place: "Lomé",
    nationality: "Togolaise",
    residence_neighborhood: "Agbalépédogan",
    phone: "+228 93 44 66 88",
    email: "h.kotoka@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "KOTOKA Honoré",
    emergency_contact_phone: "+228 93 44 66 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 420000,
    remaining_fee: 0,
  },
  {
    id: "std-825avn-24",
    registration_number: "825AVN-24",
    student_number: "ETU-2024-00825",
    last_name: "OJERINDE",
    first_name: "Safiatou Ariké",
    gender: "F",
    birth_date: "2005-12-05",
    birth_place: "Lomé",
    nationality: "Béninoise",
    residence_neighborhood: "Dékon",
    phone: "+228 90 55 77 99",
    email: "s.ojerinde@ecole-avenida.tg",
    boarder_status: "interne",
    emergency_contact_name: "OJERINDE Razak",
    emergency_contact_phone: "+229 97 12 34 56",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 420000,
    remaining_fee: 0,
  },
  {
    id: "std-826avn-24",
    registration_number: "826AVN-24",
    student_number: "ETU-2024-00826",
    last_name: "SAMA",
    first_name: "Salimata Abdoulaye",
    gender: "F",
    birth_date: "2006-05-14",
    birth_place: "Sokodé",
    nationality: "Togolaise",
    residence_neighborhood: "Tokoin Habitat",
    phone: "+228 91 66 88 00",
    email: "s.sama@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "SAMA Abdoulaye",
    emergency_contact_phone: "+228 91 66 88 11",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 340000,
    remaining_fee: 80000,
  },
  {
    id: "std-827avn-24",
    registration_number: "827AVN-24",
    student_number: "ETU-2024-00827",
    last_name: "SENA",
    first_name: "Ayoko Justine",
    gender: "F",
    birth_date: "2005-09-09",
    birth_place: "Lomé",
    nationality: "Togolaise",
    residence_neighborhood: "Hedzranawoé",
    phone: "+228 92 77 99 11",
    email: "j.sena@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "SENA Komi",
    emergency_contact_phone: "+228 92 77 99 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 420000,
    remaining_fee: 0,
  },
  {
    id: "std-828avn-24",
    registration_number: "828AVN-24",
    student_number: "ETU-2024-00828",
    last_name: "SEWAVI",
    first_name: "Adjélé Flora",
    gender: "F",
    birth_date: "2006-01-22",
    birth_place: "Aného",
    nationality: "Togolaise",
    residence_neighborhood: "Bè-Kpota",
    phone: "+228 93 88 00 22",
    email: "f.sewavi@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "SEWAVI Félix",
    emergency_contact_phone: "+228 93 88 00 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 420000,
    remaining_fee: 0,
  },
  {
    id: "std-829avn-24",
    registration_number: "829AVN-24",
    student_number: "ETU-2024-00829",
    last_name: "SONCY",
    first_name: "A. Justine",
    gender: "F",
    birth_date: "2005-08-30",
    birth_place: "Lomé",
    nationality: "Togolaise",
    residence_neighborhood: "Kodjoviakopé",
    phone: "+228 90 99 11 33",
    email: "j.soncy@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "SONCY Justin",
    emergency_contact_phone: "+228 90 99 11 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 400000,
    remaining_fee: 20000,
  },
  {
    id: "std-830avn-24",
    registration_number: "830AVN-24",
    student_number: "ETU-2024-00830",
    last_name: "SOTEO",
    first_name: "Komi B.",
    gender: "M",
    birth_date: "2004-10-15",
    birth_place: "Kpalimé",
    nationality: "Togolaise",
    residence_neighborhood: "Nyékonakpoè",
    phone: "+228 91 00 22 44",
    email: "b.soteo@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "SOTEO Bernard",
    emergency_contact_phone: "+228 91 00 22 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 420000,
    remaining_fee: 0,
  },
  {
    id: "std-831avn-24",
    registration_number: "831AVN-24",
    student_number: "ETU-2024-00831",
    last_name: "TELOU",
    first_name: "Essohona Livingstone",
    gender: "M",
    birth_date: "2004-05-27",
    birth_place: "Kara",
    nationality: "Togolaise",
    residence_neighborhood: "Agoè-Assiyéyé",
    phone: "+228 92 11 33 55",
    email: "l.telou@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "TELOU Essowaza",
    emergency_contact_phone: "+228 92 11 33 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 380000,
    remaining_fee: 40000,
  },
  {
    id: "std-832avn-24",
    registration_number: "832AVN-24",
    student_number: "ETU-2024-00832",
    last_name: "TSIKATA",
    first_name: "Komlan",
    gender: "M",
    birth_date: "2005-02-04",
    birth_place: "Lomé",
    nationality: "Togolaise",
    residence_neighborhood: "Adidogomé",
    phone: "+228 93 22 44 66",
    email: "k.tsikata@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "TSIKATA Kossi",
    emergency_contact_phone: "+228 93 22 44 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 420000,
    remaining_fee: 0,
  },
  {
    id: "std-833avn-24",
    registration_number: "833AVN-24",
    student_number: "ETU-2024-00833",
    last_name: "VODOUNOU",
    first_name: "Komlavi Audrey",
    gender: "M",
    birth_date: "2005-06-16",
    birth_place: "Lomé",
    nationality: "Togolaise",
    residence_neighborhood: "Totsi",
    phone: "+228 90 33 55 77",
    email: "a.vodounou@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "VODOUNOU Audrey Senior",
    emergency_contact_phone: "+228 90 33 55 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 420000,
    remaining_fee: 0,
  },
  {
    id: "std-834avn-24",
    registration_number: "834AVN-24",
    student_number: "ETU-2024-00834",
    last_name: "YAKA",
    first_name: "Adjo H.",
    gender: "F",
    birth_date: "2006-03-01",
    birth_place: "Vogan",
    nationality: "Togolaise",
    residence_neighborhood: "Kégué",
    phone: "+228 91 44 66 88",
    email: "h.yaka@ecole-avenida.tg",
    boarder_status: "externe",
    emergency_contact_name: "YAKA Hilaire",
    emergency_contact_phone: "+228 91 44 66 00",
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2024 - 2025",
    status: "actif",
    photo_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: 420000,
    remaining_fee: 0,
  },
];

// -------------------------------------------------------------------------
// 2. PROMOTION 2025 – 2026 : BTS 1ère Année Restauration (Page 1 & 2 - 34 Étudiants)
// -------------------------------------------------------------------------
const BTS_STUDENT_NAMES_RAW = [
  { last: "AFOLEHO", first: "Essi", gender: "F" },
  { last: "AGBAHEY", first: "Toundé Jean Chrysotome", gender: "M" },
  { last: "AGBE", first: "Solange", gender: "F" },
  { last: "AGBODAN", first: "Afi Dona Victoire", gender: "F" },
  { last: "AKAKPO", first: "Yaovi Messanh François", gender: "M" },
  { last: "AKPATCHA", first: "Abla Grace", gender: "F" },
  { last: "AMOUZOU", first: "Akossiwa Bienvenue", gender: "F" },
  { last: "AMOUZOUHOIN", first: "Koffi Vivien", gender: "M" },
  { last: "ATAKPLA", first: "Ekoué Edem Alexis", gender: "M" },
  { last: "AYA", first: "Kokou Winner", gender: "M" },
  { last: "BADAM", first: "Kokou Jean Pierre", gender: "M" },
  { last: "BEREMWOUDOUGOU", first: "S. Yasmine", gender: "F" },
  { last: "BIDA", first: "Amiratou", gender: "F" },
  { last: "COLLEY", first: "A. Edmond", gender: "M" },
  { last: "d'ALMEIDA", first: "Ayi Larissio", gender: "M" },
  { last: "DE SOUZA", first: "Afi Cylvia", gender: "F" },
  { last: "DICKEWU", first: "Afi Williana", gender: "F" },
  { last: "DOMEGNI", first: "Léa Elie", gender: "F" },
  { last: "DOSSOU", first: "Abla Dona", gender: "F" },
  { last: "DOSSOU", first: "Yayra Sandrine", gender: "F" },
  { last: "EDOH", first: "Silvère", gender: "M" },
  { last: "EYOU", first: "Adjo Georgette", gender: "F" },
  { last: "HUNKPEVI", first: "Yaovi", gender: "M" },
  { last: "KOTOKA", first: "Afi Honorine", gender: "F" },
  { last: "OJERINDE", first: "Safiatou Ariké", gender: "F" },
  { last: "SAMA", first: "Salimata Abdoulaye", gender: "F" },
  { last: "SENA", first: "Ayoko Justine", gender: "F" },
  { last: "SEWAVI", first: "Adjélé Flora", gender: "F" },
  { last: "SONCY", first: "A. Justine", gender: "F" },
  { last: "SOTEO", first: "Komi B.", gender: "M" },
  { last: "TELOU", first: "Essohona Livingstone", gender: "M" },
  { last: "TSIKATA", first: "Komlan", gender: "M" },
  { last: "VODOUNOU", first: "Komlavi Audrey", gender: "M" },
  { last: "YAKA", first: "Adjo H.", gender: "F" },
];

export const STUDENTS_2025_2026_BTS: Student[] = BTS_STUDENT_NAMES_RAW.map((s, idx) => {
  const num = String(idx + 1).padStart(2, "0");
  const hood = LOME_NEIGHBORHOODS[idx % LOME_NEIGHBORHOODS.length];
  const paid = (idx * 30000 + 200000) % 420000;

  return {
    id: `std-8${num}avn-25`,
    registration_number: `8${num}AVN-25`,
    student_number: `ETU-2025-008${num}`,
    last_name: s.last,
    first_name: s.first,
    gender: s.gender as "M" | "F",
    birth_date: `2005-0${(idx % 9) + 1}-15`,
    birth_place: idx % 3 === 0 ? "Aného" : idx % 2 === 0 ? "Kpalimé" : "Lomé",
    nationality: "Togolaise",
    residence_neighborhood: hood,
    phone: `+228 9${idx % 4} ${String(10 + idx * 2)} ${String(20 + idx * 2)} ${String(30 + idx * 2)}`,
    email: `${s.first.toLowerCase().split(" ")[0]}.${s.last.toLowerCase()}@ecole-avenida.tg`,
    boarder_status: idx % 5 === 0 ? "interne" : "externe",
    emergency_contact_name: `${s.last} Parent`,
    emergency_contact_phone: `+228 90 00 00 ${num}`,
    program_code: "BTS",
    class_name: "BTS1 - Restauration",
    academic_year: "2025 - 2026",
    status: "actif",
    photo_url:
      s.gender === "F"
        ? "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop"
        : "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop",
    total_fee: 420000,
    paid_fee: paid,
    remaining_fee: 420000 - paid,
  };
});

// -------------------------------------------------------------------------
// 3. PROMOTION 2025 – 2026 : SESSION MAI (CAP & CFA - Page 5, 6, 7 - 12 Étudiants)
// -------------------------------------------------------------------------
const SESSION_MAI_NAMES = [
  { last: "ADADEVI", first: "Akossiwa Jeannette", prog: "CAP", gender: "F" },
  { last: "ADJANOU", first: "Ayawa Debora", prog: "CFA", gender: "F" },
  { last: "AFOLABI", first: "Tayé Etsri", prog: "CFA", gender: "M" },
  { last: "AMONI", first: "Kotsè Fernando", prog: "CAP", gender: "M" },
  { last: "DADO", first: "Afi Victoire", prog: "CFA", gender: "F" },
  { last: "GBADJAVI", first: "Koffi D. Junior", prog: "CAP", gender: "M" },
  { last: "KPAKPO", first: "Gisèle", prog: "CFA", gender: "F" },
  { last: "KPODZRO", first: "Komi Guy", prog: "CAP", gender: "M" },
  { last: "MENSAH", first: "Tèlé Débora", prog: "CAP", gender: "F" },
  { last: "SOULEMANE", first: "B. Souley", prog: "CAP", gender: "M" },
  { last: "TEVI BENISSAN", first: "Mablé", prog: "CFA", gender: "F" },
  { last: "WALLACE", first: "Etsri A.J.", prog: "CFA", gender: "M" },
];

export const STUDENTS_2025_2026_MAI: Student[] = SESSION_MAI_NAMES.map((s, idx) => {
  const regNum = 35 + idx;
  const hood = LOME_NEIGHBORHOODS[idx % LOME_NEIGHBORHOODS.length];
  const fee = s.prog === "CAP" ? 280000 : 260000;
  const paid = idx % 2 === 0 ? fee : Math.round(fee * 0.7);

  return {
    id: `std-8${regNum}avn-25`,
    registration_number: `8${regNum}AVN-25`,
    student_number: `ETU-2025-008${regNum}`,
    last_name: s.last,
    first_name: s.first,
    gender: s.gender as "M" | "F",
    birth_date: `2006-0${(idx % 8) + 2}-11`,
    birth_place: "Lomé",
    nationality: "Togolaise",
    residence_neighborhood: hood,
    phone: `+228 92 ${String(40 + idx * 3)} ${String(50 + idx * 2)} ${String(10 + idx)}`,
    email: `${s.first.toLowerCase().split(" ")[0]}.${s.last.toLowerCase().replace(/\s+/g, "")}@ecole-avenida.tg`,
    boarder_status: "externe",
    emergency_contact_name: `${s.last} Responsable`,
    emergency_contact_phone: `+228 92 00 00 ${regNum}`,
    program_code: s.prog as any,
    class_name: `${s.prog} - Session Mai`,
    academic_year: "2025 - 2026",
    status: "actif",
    photo_url:
      s.gender === "F"
        ? "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&h=200&fit=crop"
        : "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop",
    total_fee: fee,
    paid_fee: paid,
    remaining_fee: fee - paid,
  };
});

// -------------------------------------------------------------------------
// 4. PROMOTION 2025 – 2026 : CAP 1 / CFA & MOD (Page 8 - 38 Étudiants)
// -------------------------------------------------------------------------
const CAP1_CFA_MOD_NAMES = [
  { last: "ABALO", first: "Zakyatou", prog: "CAP", gender: "F" },
  { last: "AFANMALON", first: "Yaovi Yves", prog: "CAP", gender: "M" },
  { last: "AGBENEME", first: "Rolande", prog: "CAP", gender: "F" },
  { last: "AHONSOU", first: "A. G. Chantal", prog: "CFA", gender: "F" },
  { last: "AHUADJOGBE", first: "Essi Emmanuella", prog: "CAP", gender: "F" },
  { last: "AKANGNAN", first: "Augustin", prog: "CAP", gender: "M" },
  { last: "ALI", first: "Oumou", prog: "CFA", gender: "F" },
  { last: "ATISO", first: "Elom Crédo", prog: "CAP", gender: "M" },
  { last: "AVOSSE", first: "Samuel", prog: "CAP", gender: "M" },
  { last: "AZAGLO", first: "Emmanuella", prog: "CAP", gender: "F" },
  { last: "AZIAGBEDE", first: "Julienne", prog: "CAP", gender: "F" },
  { last: "AZINDJE", first: "Madeleine", prog: "CFA", gender: "F" },
  { last: "AZINDJE", first: "Marie", prog: "CFA", gender: "F" },
  { last: "BAYOR", first: "Agar-Kenza", prog: "CAP", gender: "F" },
  { last: "BOKOVI", first: "Elize", prog: "CAP", gender: "F" },
  { last: "D’ALMEIDA", first: "Joanita", prog: "CAP", gender: "F" },
  { last: "EBOAHUN", first: "Essie Melissa", prog: "CAP", gender: "F" },
  { last: "FIONOU", first: "Jeanne", prog: "CFA", gender: "F" },
  { last: "HOUNDEALO", first: "Mathilde", prog: "CAP", gender: "F" },
  { last: "HOUNKANLIN", first: "Princia Firmène", prog: "CAP", gender: "F" },
  { last: "HOUNKPATI", first: "Rémi", prog: "CAP", gender: "M" },
  { last: "KAFANDO", first: "Fidel", prog: "CAP", gender: "M" },
  { last: "KANGNI", first: "Majestée", prog: "CAP", gender: "F" },
  { last: "KANTE", first: "Bintou", prog: "CFA", gender: "F" },
  { last: "KLU", first: "Kossiwa Ella", prog: "CAP", gender: "F" },
  { last: "KPOTOLI", first: "Wilfried", prog: "CAP", gender: "M" },
  { last: "MAMAH", first: "Jalila", prog: "CAP", gender: "F" },
  { last: "N ‘GNAMA", first: "Kokou Romain Edouard", prog: "CAP", gender: "M" },
  { last: "SAOUGOU", first: "Barikissou", prog: "CFA", gender: "F" },
  { last: "TANIMAMA", first: "Rafatath", prog: "CAP", gender: "F" },
  { last: "TEDJI", first: "Afi Françoise", prog: "CAP", gender: "F" },
  { last: "TEKO", first: "Dédé Cathérine", prog: "CAP", gender: "F" },
  { last: "TETE", first: "Ehonam Dénise", prog: "CAP", gender: "F" },
  { last: "YACOUBOU", first: "Faridatou", prog: "CAP", gender: "F" },
  { last: "YEVESSIN", first: "Estelle", prog: "CAP", gender: "F" },
  { last: "YIKPOVI", first: "Gniningan", prog: "CAP", gender: "M" },
  { last: "ZINSOU", first: "Adjo Anita", prog: "CAP", gender: "F" },
  { last: "ZINZINA", first: "Daniella", prog: "CAP", gender: "F" },
];

export const STUDENTS_2025_2026_CAP1: Student[] = CAP1_CFA_MOD_NAMES.map((s, idx) => {
  const regNum = 47 + idx;
  const hood = LOME_NEIGHBORHOODS[idx % LOME_NEIGHBORHOODS.length];
  const fee = s.prog === "CAP" ? 280000 : 260000;
  const paid = (idx * 25000 + 150000) % fee;

  return {
    id: `std-8${regNum}avn-25`,
    registration_number: `8${regNum}AVN-25`,
    student_number: `ETU-2025-008${regNum}`,
    last_name: s.last,
    first_name: s.first,
    gender: s.gender as "M" | "F",
    birth_date: `2006-0${(idx % 9) + 1}-20`,
    birth_place: idx % 4 === 0 ? "Kpalimé" : idx % 3 === 0 ? "Atakpamé" : "Lomé",
    nationality: "Togolaise",
    residence_neighborhood: hood,
    phone: `+228 9${idx % 4} ${String(11 + idx)} ${String(22 + idx)} ${String(33 + idx)}`,
    email: `${s.first.toLowerCase().split(" ")[0].replace(/[^a-z]/g, "")}.${s.last.toLowerCase().replace(/[^a-z]/g, "")}@ecole-avenida.tg`,
    boarder_status: idx % 6 === 0 ? "interne" : "externe",
    emergency_contact_name: `${s.last} Parent Tuteur`,
    emergency_contact_phone: `+228 90 00 00 ${regNum}`,
    program_code: s.prog as any,
    class_name: s.prog === "CAP" ? "CAP1 - Cuisine & Mod" : "CFA - Pâtisserie & Mod",
    academic_year: "2025 - 2026",
    status: "actif",
    photo_url:
      s.gender === "F"
        ? "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop"
        : "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop",
    total_fee: fee,
    paid_fee: paid,
    remaining_fee: fee - paid,
  };
});

// -------------------------------------------------------------------------
// 5. PROMOTION 2026 – 2027 : BTS 2ème Année (Poursuite des études - 34 Étudiants)
// -------------------------------------------------------------------------
export const STUDENTS_2026_2027: Student[] = BTS_STUDENT_NAMES_RAW.map((s, idx) => {
  const num = String(idx + 1).padStart(2, "0");
  const hood = LOME_NEIGHBORHOODS[idx % LOME_NEIGHBORHOODS.length];
  const fee = 420000;
  const paid = (idx * 35000 + 180000) % fee;

  return {
    id: `std-8${num}avn-26`,
    registration_number: `8${num}AVN-26`,
    student_number: `ETU-2026-008${num}`,
    last_name: s.last,
    first_name: s.first,
    gender: s.gender as "M" | "F",
    birth_date: `2005-0${(idx % 9) + 1}-15`,
    birth_place: "Lomé",
    nationality: "Togolaise",
    residence_neighborhood: hood,
    phone: `+228 9${idx % 4} ${String(15 + idx * 2)} ${String(25 + idx * 2)} ${String(35 + idx * 2)}`,
    email: `${s.first.toLowerCase().split(" ")[0]}.${s.last.toLowerCase()}@ecole-avenida.tg`,
    boarder_status: idx % 4 === 0 ? "interne" : "externe",
    emergency_contact_name: `${s.last} Tuteur`,
    emergency_contact_phone: `+228 90 00 00 ${num}`,
    program_code: "BTS",
    class_name: "BTS2 - Restauration & Management",
    academic_year: "2026 - 2027",
    status: "actif",
    photo_url:
      s.gender === "F"
        ? "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200&h=200&fit=crop"
        : "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&h=200&fit=crop",
    total_fee: fee,
    paid_fee: paid,
    remaining_fee: fee - paid,
  };
});

// -------------------------------------------------------------------------
// TABLE GLOBALE CONSOLIDÉE DE TOUS LES ÉLÈVES RECONNUS
// -------------------------------------------------------------------------
export const ALL_REAL_STUDENTS: Student[] = [
  ...STUDENTS_2024_2025,
  ...STUDENTS_2025_2026_BTS,
  ...STUDENTS_2025_2026_MAI,
  ...STUDENTS_2025_2026_CAP1,
  ...STUDENTS_2026_2027,
];
